<a href="https://colab.research.google.com/github/woongjoonchoi/Tutorials/blob/main/Numpy/numpy_stride_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Practice from : https://towardsdatascience.com/advanced-numpy-master-stride-tricks-with-25-illustrated-exercises-923a9393ab20#9c37

# 1D exercise

1) slice first 3 elements

In [6]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(3,) , strides =(1,))
print(x)

[1 2 3]


similar

In [7]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)
print(x[0,:3])

[1 2 3]


2)slice first 8 elements

In [ ]:
x= np.asarray(range(1,26) , np.int8).reshape(5,5)

x= np.lib.stride_tricks.as_strided(x,shape=(8,) , strides=(1,))

print(x)

[1 2 3 4 5 6 7 8]


simliar


In [10]:
x= np.asarray(range(1,26) , np.int8).reshape(5,5)

print(x[0,:8])


[1 2 3 4 5]


3)flatten 2-d array  
input item: 2bytes

In [ ]:
x = np.asarray(range(1,26) , np.int16).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(25,) ,strides =(2,))
# a=np.array([1,3])
print(x)
# print(a is np.asarray(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


similar

In [11]:
x = np.asarray(range(1,26) , np.int16).reshape(5,5)
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25], dtype=int16)

4) skipe every other element
input item : 1bytes

In [ ]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)
x = np.lib.stride_tricks.as_strided(x,shape=(3,),strides=(2,))
print(x)

[1 3 5]


5)slice first column  
input item : 8 bytes

In [ ]:
x = np.asarray(range(1,26) , np.int64).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(5,),strides =(40,) )
print(x)

[ 1  6 11 16 21]


similar

In [12]:
x = np.asarray(range(1,26) , np.int64).reshape(5,5)

x[0,::2]

array([1, 3, 5])

6)diagonal element  
input item : 8 bytes

In [ ]:
x= np.asarray(range(1,26) , np.int64).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(5,),strides=(48,))
print(x)

[ 1  7 13 19 25]


similar

In [13]:
x= np.asarray(range(1,26) , np.int64).reshape(5,5)
x.diagonal()

array([ 1,  7, 13, 19, 25])

7)repeat element  
input item : 8 bytes

In [ ]:
x=np.asarray(range(1,26) , np.int64 ).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x , shape=(5,) , strides=(0,))
print(x)

[1 1 1 1 1]


simliar

# 2D -exercise

8) simple 2d slicing

In [ ]:
x=np.asarray(range(1,26) , np.int64).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(4,3) , strides=(40,8))
print(x)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]


9) Slice a zigzag

Input itemsize: 8 bytes | Input strides: (40, 8)

In [3]:
x = np.asarray(range(1,26) , np.int64).reshape(5,5)
x = np.lib.stride_tricks.as_strided(x,shape=(4,2),strides=(48,8))
print(x)

[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]]


10 ) sparse strding
input itemsize : 8 bytes 

In [5]:
x = np.asarray(range(1,26) , np.int64 ).reshape(5,5)
x = np.lib.stride_tricks.as_strided(x, shape = (3,3) , strides = (80,16))
print(x)

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


similar


In [14]:
x = np.asarray(range(1,26) , np.int64).reshape(5,5)
x[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

11 ) Transpose a 2d array  
input item size : 1 byte

In [17]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)
np.lib.stride_tricks.as_strided(x,shape=(3,3),strides =(1,5) )


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

similar

In [18]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)

x[:3,:3].T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

12 ) repeat first column 4 times  
input item size : 4 bytes

In [19]:
x = np.asarray(range(1,26) , np.int32).reshape(5,5)

np.lib.stride_tricks.as_strided(x,shape=(5,4),strides=(20,0))

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int32)

similar

In [20]:
x = np.asarray(range(1,26) , np.int32).reshape(5,5)

np.broadcast_to(x[:,0,None], (5,4))

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int32)

13 ) 