<a href="https://colab.research.google.com/github/woongjoonchoi/Tutorials/blob/main/Numpy/Numpytutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

array의 생성

Q  . [1,2,3,4,5] 라는 array로 부터 ndarray를 생성하시오

In [ ]:
a=[1,2,3,4,5]
b=[5,4,3,2,1]

In [ ]:
a = np.array(a , int)

In [ ]:
a


array([1, 2, 3, 4, 5])

In [ ]:
test_array= np.array([" 1" , "4" , 5.0 ,8] , float) 
test_array


NameError: ignored

[" 1" , "4" , 5.0 ,8]

array([1., 4., 5., 8.])

In [ ]:
type((test_array))

numpy.ndarray

In [ ]:
type(test_array[3])

numpy.float64

numpy array vs python arary

boostcamp pdf 참조

a = [1,2,3,4,5]
b= [ 5,4,3,2,1]  

a,b에 들어있는 1들을 비교

In [ ]:
a = [1,2,3,4,5]
b= [ 5,4,3,2,1]

a[0] is b[-1]

True

True

numpy array의 1을 비교

In [ ]:
a = np.array(a)
b= np.array(b)

a[0] is b[-1]

False

test_array 의 dtype , shape , 을 반환

In [ ]:
test_array.dtype

dtype('float64')

In [ ]:
test_array.shape

(4,)

In [ ]:
np.array(a).shape

(5,)

1차원 ,2차원 3차원 텐서 표현

차원이 늘어나면 랭크가 오른쪽으로 한칸 밀림

In [ ]:
tensor = [1,2 ,5,8]
tensor = np.array(tensor , dtype = int)
tensor.shape

(4,)

In [ ]:
tensor.dtype

dtype('int64')

In [ ]:
tensor = [[1,2 ,5,8] , [1,2 ,5,8] ,[1,2 ,5,8]]
tensor = np.array(tensor,dtype=int)

In [ ]:
tensor.dtype

dtype('int64')

In [ ]:
tensor.shape

(3, 4)

In [ ]:
tensor = [[[1,2 ,5,8] , [1,2 ,5,8] ,[1,2 ,5,8]] ,
          [[1,2 ,5,8] , [1,2 ,5,8] ,[1,2 ,5,8]] ,
          [[1,2 ,5,8] , [1,2 ,5,8] ,[1,2 ,5,8]] ]
tensor = np.array(tensor, dtype = int)

In [ ]:
tensor.dtype

dtype('int64')

In [ ]:
tensor.shape

(3, 3, 4)

nbytes- ndarray object의 메모리 크기를 반환

In [ ]:
a = np.array([[1,2,3] , [4.5,5,6]] ,  dtype = np.int8)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [ ]:
a.dtype

dtype('int8')

In [ ]:
a.nbytes

6

In [ ]:
np.array([[1,2,3] , [4.5 , "5" , "6"] ] ,dtype = np.float32).nbytes

24

In [ ]:
np.array([[1,2,3] ,[4.5 , "5" , "6"]] ,dtype = np.int32  ).nbytes

24

In [ ]:
np.array([[1,2,3] ,[4.5 , "5" , "6"]] ,dtype = np.float64).nbytes

48

Handling shape

In [ ]:
import numpy as np

In [ ]:
test_matrix =[[1,2,3,4] , [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [ ]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [ ]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [ ]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

-1  : size 기준  
아래 예제는 전체 size가 8이므로 , 4 *2 이기 때문에 4가나온다.

In [ ]:
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [ ]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [ ]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

1,-1,2 이면  
1*2 *4 = 8이므로 -1쪽은 4 가된다

In [ ]:
np.array(test_matrix).reshape(1,-1,2).shape

(1, 4, 2)

flatten : reshape의 기능중 하나를 가져옴

In [ ]:
test_matrix = [[[1,2,3,4] , [5,6,7,8]] ,[[1,2,3,4] , [5,6,7,8]]]

In [ ]:
test_matrix = np.array(test_matrix)
test_matrix.shape

(2, 2, 4)

In [ ]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.array(test_matrix).flatten().shape

(16,)

list와 달리 이차원 배열에서 [0,0] 표기법을 제공한다.   

matrix의 경우 앞은 row 뒤는  column이다.

In [ ]:
test_example = np.array([[1,2,3] , [4.5,5,6]] , int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
test_example[0][2]

3

In [ ]:
test_example[0,2]

3

In [ ]:
test_example[0,0] = 10
test_example

array([[10,  2,  3],
       [ 4,  5,  6]])

In [ ]:
test_example[1,2] = 5
test_example

array([[10,  2,  3],
       [ 4,  5,  5]])

list와 달리 행과 열 부분을 나눠서 slicing이 가능함   
matrix의 부분집합으 ㄹ추출할 때 유용


[i, j]] -> i행 j열  

[i : j]  -> i~j행

In [ ]:
test_example = np.array([[1,2,5,8] ,[1,2,5,8] ,[1,2,5,8] ,[1,2,5,8]])
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [ ]:
test_example[:,2]  #  2열

array([5, 5, 5, 5])

In [ ]:
test_example  #  추출해서 반환 , 바꾸는 것이 아니다.

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [ ]:
test_example[:,1:3].shape  # 1~2행

(4, 2)

In [ ]:
test_example  

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [ ]:
test_example[1:2,:2]  # 1행 , 0열~1열

array([[1, 2]])

In [ ]:
test_example[1]  # 1 Row의 모든 값

array([1, 2, 5, 8])

In [ ]:
test_example[1:3]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [ ]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a[:,-1]  # 마지막 열

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

arr[:,::2]  -> start point, endpoint , steps 

create function


arange

In [ ]:
list(range(0,10,3))

[0, 3, 6, 9]

In [ ]:
type(list(range(30)))

list

In [ ]:
#arange: liste의 range와 같은효과


np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

zeros - 0 으로  가득찬 ndarray 생성

np.zeros(shape,dtype , order)

ones  - 1 로 가득찬 ndarray 생성

np.ones(shape,dtype , order)


emtpy - shpae 만 주어지고 비어있는 ndarray 생성

(memory initialization 이 되지않ㅇ음)

공간만 잡아줌 . 그 공간에 이전에쓰이던 값이 남아있음을 알 수 있음


something_like

ex .) ones_like

In [ ]:
np.zeros(shape = (10,) , dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [ ]:
np.zeros((2,5) )

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape = (10,) ,dtype = np.int8 )

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.empty(shape = (10, ) , dtype = np.int8)

array([ 32,  53, 125, -14, 117,  85,   0,   0,   3,   0], dtype=int8)

In [ ]:
test_matrix = np.arange(100).reshape(5,-1)
test_matrix.shape

(5, 20)

# 2022-01-04

identity : 단위행렬을 생성함

Q : 3,3 shape의 단위 행렬을 만드시오 . 단 , 크기는 9byte여야 하오  
Q2 : 5,5 shape 단위 행렬을 만드시오



eye : 대각선이 1인 행렬 , k 값의 시작 index 변경가능


identity 와 다르게 행,열 shape, index 시작 위치를 정할 수 있다.


Q1 . 3 ,3 shape의 단위 행렬을 eye를 이용해 만드시오  
Q2 . shape 3, 5의 index 1  을 시작점으로 대각선이 1인 행렬을 만드시오  
Q3 . shape 3, 5 인 index 0를 시작점으로
대각선인 1인 행렬을 만드시오  
단 , argument로 N,M , 크기는 8bytes여야하오

diag : 대각 행렬의 값을 추출함


Q1 : 0~ 9 값으로 3,3 shape의 행렬을 만들고
대각 선 성분을 추출하시오
Q2 ; 0~ 9 값으로 3,3 shape의 행렬을 만들고
index 1부터의 대각성분을 추출하시오

random sampling - 데이터 분포에 따른 sampling으로 array를 생성  
argument로 모수 값(parameter)를 줌

Q1 .0~1 사이의 값을 가지는 균등 분포에서 10개를 sampling하고 2,5 shape으로 reshape 하시오

Q2. parameter를 0,1로 가지는 정규 분포에서 10개를 sampling 하고 2,5 shape으로 reshape 하시오

## Operation


Sum - ndarray 의 element 간의 합을 구함

In [ ]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
test_array.sum(dtype=np.float)

55.0