<a href="https://colab.research.google.com/github/woongjoonchoi/Tutorials/blob/main/Numpy/Numpytutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

array의 생성

In [ ]:
a=[1,2,3,4,5]
b=[5,4,3,2,1]

In [ ]:
a = np.array(a , int)

In [ ]:
a


array([1, 2, 3, 4, 5])

In [ ]:
test_array= np.array([" 1" , "4" , 5.0 ,8] , float) 
test_array


array([1., 4., 5., 8.])

In [ ]:
type((test_array))

numpy.ndarray

In [ ]:
type(test_array[3])

numpy.float64

numpy array vs python arary

boostcamp pdf 참조

a = [1,2,3,4,5]
b= [ 5,4,3,2,1]  

a,b에 들어있는 1들을 비교

In [ ]:
a = [1,2,3,4,5]
b= [ 5,4,3,2,1]

a[0] is b[-1]

True

True

numpy array의 1을 비교

In [ ]:
a = np.array(a)
b= np.array(b)

a[0] is b[-1]

False

test_array 의 dtype , shape , 을 반환

In [ ]:
test_array.dtype

dtype('float64')

In [ ]:
test_array.shape

(4,)

In [ ]:
np.array(a).shape

(5,)

1차원 ,2차원 3차원 텐서 표현

차원이 늘어나면 랭크가 오른쪽으로 한칸 밀림

In [ ]:
tensor = [1,2 ,5,8]
tensor = np.array(tensor , dtype = int)
tensor.shape

(4,)

In [ ]:
tensor.dtype

dtype('int64')

In [ ]:
tensor = [[1,2 ,5,8] , [1,2 ,5,8] ,[1,2 ,5,8]]
tensor = np.array(tensor,dtype=int)

In [ ]:
tensor.dtype

dtype('int64')

In [ ]:
tensor.shape

(3, 4)

In [ ]:
tensor = [[[1,2 ,5,8] , [1,2 ,5,8] ,[1,2 ,5,8]] ,
          [[1,2 ,5,8] , [1,2 ,5,8] ,[1,2 ,5,8]] ,
          [[1,2 ,5,8] , [1,2 ,5,8] ,[1,2 ,5,8]] ]
tensor = np.array(tensor, dtype = int)

In [ ]:
tensor.dtype

dtype('int64')

In [ ]:
tensor.shape

(3, 3, 4)

nbytes- ndarray object의 메모리 크기를 반환

In [ ]:
a = np.array([[1,2,3] , [4.5,5,6]] ,  dtype = np.int8)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [ ]:
a.dtype

dtype('int8')

In [ ]:
a.nbytes

6

In [ ]:
np.array([[1,2,3] , [4.5 , "5" , "6"] ] ,dtype = np.float32).nbytes

24

In [ ]:
np.array([[1,2,3] ,[4.5 , "5" , "6"]] ,dtype = np.int32  ).nbytes

24

In [ ]:
np.array([[1,2,3] ,[4.5 , "5" , "6"]] ,dtype = np.float64).nbytes

48