<a href="https://colab.research.google.com/github/woongjoonchoi/Tutorials/blob/main/Numpy/numpy_stride_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Practice from : https://towardsdatascience.com/advanced-numpy-master-stride-tricks-with-25-illustrated-exercises-923a9393ab20#9c37

# 1D exercise

1) slice first 3 elements

In [ ]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(3,) , strides =(1,))
print(x)

[1 2 3]


2)slice first 8 elements

In [4]:
x= np.asarray(range(1,26) , np.int8).reshape(5,5)

x= np.lib.stride_tricks.as_strided(x,shape=(8,) , strides=(1,))

print(x)

[1 2 3 4 5 6 7 8]


3)flatten 2-d array  
input item: 2bytes

In [9]:
x = np.asarray(range(1,26) , np.int16).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(25,) ,strides =(2,))
# a=np.array([1,3])
print(x)
# print(a is np.asarray(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


4) skipe every other element
input item : 1bytes

In [13]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)
x = np.lib.stride_tricks.as_strided(x,shape=(3,),strides=(2,))
print(x)

[1 3 5]


5)slice first column  
input item : 8 bytes

In [15]:
x = np.asarray(range(1,26) , np.int64).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(5,),strides =(40,) )
print(x)

[ 1  6 11 16 21]


6)diagonal element  
input item : 8 bytes

In [16]:
x= np.asarray(range(1,26) , np.int64).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(5,),strides=(48,))
print(x)

[ 1  7 13 19 25]


7)repeat element  
input item : 8 bytes

In [18]:
x=np.asarray(range(1,26) , np.int64 ).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x , shape=(5,) , strides=(0,))
print(x)

[1 1 1 1 1]


# 2D -exercise

In [19]:
x=np.asarray(range(1,26) , np.int64).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(4,3) , strides=(40,8))
print(x)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
