<a href="https://colab.research.google.com/github/woongjoonchoi/Tutorials/blob/main/Numpy/numpy_stride_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Practice from : https://towardsdatascience.com/advanced-numpy-master-stride-tricks-with-25-illustrated-exercises-923a9393ab20#9c37

# 1D exercise

1) slice first 3 elements

In [ ]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(3,) , strides =(1,))
print(x)

[1 2 3]


similar

In [ ]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)
print(x[0,:3])

[1 2 3]


2)slice first 8 elements

In [ ]:
x= np.asarray(range(1,26) , np.int8).reshape(5,5)

x= np.lib.stride_tricks.as_strided(x,shape=(8,) , strides=(1,))

print(x)

[1 2 3 4 5 6 7 8]


simliar


In [ ]:
x= np.asarray(range(1,26) , np.int8).reshape(5,5)

print(x[0,:8])


[1 2 3 4 5]


3)flatten 2-d array  
input item: 2bytes

In [ ]:
x = np.asarray(range(1,26) , np.int16).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(25,) ,strides =(2,))
# a=np.array([1,3])
print(x)
# print(a is np.asarray(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


similar

In [ ]:
x = np.asarray(range(1,26) , np.int16).reshape(5,5)
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25], dtype=int16)

4) skipe every other element
input item : 1bytes

In [ ]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)
x = np.lib.stride_tricks.as_strided(x,shape=(3,),strides=(2,))
print(x)

[1 3 5]


5)slice first column  
input item : 8 bytes

In [ ]:
x = np.asarray(range(1,26) , np.int64).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(5,),strides =(40,) )
print(x)

[ 1  6 11 16 21]


similar

In [ ]:
x = np.asarray(range(1,26) , np.int64).reshape(5,5)

x[0,::2]

array([1, 3, 5])

6)diagonal element  
input item : 8 bytes

In [ ]:
x= np.asarray(range(1,26) , np.int64).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(5,),strides=(48,))
print(x)

[ 1  7 13 19 25]


similar

In [ ]:
x= np.asarray(range(1,26) , np.int64).reshape(5,5)
x.diagonal()

array([ 1,  7, 13, 19, 25])

7)repeat element  
input item : 8 bytes

In [ ]:
x=np.asarray(range(1,26) , np.int64 ).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x , shape=(5,) , strides=(0,))
print(x)

[1 1 1 1 1]


simliar

# 2D -exercise

8) simple 2d slicing

In [ ]:
x=np.asarray(range(1,26) , np.int64).reshape(5,5)
x=np.lib.stride_tricks.as_strided(x,shape=(4,3) , strides=(40,8))
print(x)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]


9) Slice a zigzag

Input itemsize: 8 bytes | Input strides: (40, 8)

In [ ]:
x = np.asarray(range(1,26) , np.int64).reshape(5,5)
x = np.lib.stride_tricks.as_strided(x,shape=(4,2),strides=(48,8))
print(x)

[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]]


10 ) sparse strding
input itemsize : 8 bytes 

In [ ]:
x = np.asarray(range(1,26) , np.int64 ).reshape(5,5)
x = np.lib.stride_tricks.as_strided(x, shape = (3,3) , strides = (80,16))
print(x)

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


similar


In [ ]:
x = np.asarray(range(1,26) , np.int64).reshape(5,5)
x[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

11 ) Transpose a 2d array  
input item size : 1 byte

In [ ]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)
np.lib.stride_tricks.as_strided(x,shape=(3,3),strides =(1,5) )


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

similar

In [ ]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)

x[:3,:3].T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

12 ) repeat first column 4 times  
input item size : 4 bytes

In [ ]:
x = np.asarray(range(1,26) , np.int32).reshape(5,5)

np.lib.stride_tricks.as_strided(x,shape=(5,4),strides=(20,0))

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int32)

similar

In [ ]:
x = np.asarray(range(1,26) , np.int32).reshape(5,5)

np.broadcast_to(x[:,0,None], (5,4))

array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int32)

13 )  reshape 1d array  
nput itemsize: 8 bytes | Input strides: (8,)

In [5]:
x = np.asarray(range(1,13) , np.int64 )

np.lib.stride_tricks.as_strided(x,shape=(4,3) , strides = (24,8) )


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

similar

In [7]:
x.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

14) Slide a 1D window  

Input itemsize: 1 byte | Input strides: (1,

In [9]:
x = np.asarray(range(1,11) , np.int8) 

np.lib.stride_tricks.as_strided(x , shape = (8,3) , strides = (1,1))

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]], dtype=int8)

similar

In [ ]:
# 이것을 할 수 있는 method가 없다.

15 ) Slide a 2D window then flatten   
  
nput itemsize: 1 byte | Input strides: (2, 1


In [11]:
x = np.asarray(         [0,1,10,11,20,21,30,31,40,41,50,51],np.int8).reshape(6,2)

np.lib.stride_tricks.as_strided(x , shape=(4,6) , strides = (2,1))

array([[ 0,  1, 10, 11, 20, 21],
       [10, 11, 20, 21, 30, 31],
       [20, 21, 30, 31, 40, 41],
       [30, 31, 40, 41, 50, 51]], dtype=int8)

similar

In [ ]:
# 이것을 비슷하게 할 수는 없다.


16 ) collapse an axis from an 3-D array  
Input itemsize: 1 byte | 

In [12]:
x = np.asarray(range(1,13),np.int8).reshape(3,2,2)

np.lib.stride_tricks.as_strided(x, shape = (3,4) , strides = (4,1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)

similar

In [13]:
x.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)

# 3D exercises

17) 2 cornsers  
Input itemsize: 2 bytes

In [15]:
x = np.asarray(range(1,26) , np.int16).reshape(5,5)

np.lib.stride_tricks.as_strided(x , shape = (2,2,2) ,strides = (30,10,2))

array([[[ 1,  2],
        [ 6,  7]],

       [[16, 17],
        [21, 22]]], dtype=int16)

similar

In [ ]:
 # this may not be achieved concisely

18 ) Straggered Slicing  
Inputitem 1bytes

In [16]:
x = np.asarray(range(1,26) , np.int8).reshape(5,5)

np.lib.stride_tricks.as_strided(x , shape=(2,2,3 ), strides = (10,6,1))

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [17, 18, 19]]], dtype=int8)

similar

In [ ]:
# method로 비슷한게 없다. 

19 ) Repeat a 2D array  
input item 2bytes


In [18]:
x = np.asarray(range(1,26) , np.int16).reshape(5,5)

np.lib.stride_tricks.as_strided(x , shape=(3,2,4) , strides = (0,10,2))

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]]], dtype=int16)

similar

In [ ]:
#  method로 비슷한게 없다.

20 ) 3D transpose  
Input item 4bytes

In [20]:
x = np.asarray(range(1,13) , np.int32).reshape(3,2,2)

np.lib.stride_tricks.as_strided(x , shape=(3,2,2) , strides = (16,4,8))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]], dtype=int32)

similar

In [21]:
np.swapaxes(x,1,2)

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]], dtype=int32)

21) slide 2d array  
Input item ; 8bytes

In [22]:
x = np.asarray(range(1,21) , np.int64).reshape(4,5)

np.lib.stride_tricks.as_strided(x, shape = (3,2,5) , strides = (40,40,8))

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

similar

In [ ]:
#  method로 할 수 없다. 

22 ) Reshape 1 d array to 3d   
input item : 1bytes

In [23]:
x = np.asarray(range(1,13) , np.int8)

np.lib.stride_tricks.as_strided(x,shape=(2,2,3) , strides = ( 6,3,1))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int8)

similar

In [24]:
x.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int8)

# 4D exrcises

23 ) Slide a 2D respective field for convolutions  
input item : 1bytes

In [28]:
x = np.asarray(range(1,26) , np.int8)

np.lib.stride_tricks.as_strided(x, shape =(2,2,3,3) , strides =(10,2,5,1))

array([[[[ 1,  2,  3],
         [ 6,  7,  8],
         [11, 12, 13]],

        [[ 3,  4,  5],
         [ 8,  9, 10],
         [13, 14, 15]]],


       [[[11, 12, 13],
         [16, 17, 18],
         [21, 22, 23]],

        [[13, 14, 15],
         [18, 19, 20],
         [23, 24, 25]]]], dtype=int8)

similar

In [ ]:
#  no simliar method

24) Repeat a 3D tensor  

input item : 8 bytes

In [29]:
x = np.asarray(range(1,13) , np.int64).reshape(2,2,3)

np.lib.stride_tricks.as_strided(x, shape =(2,2,2,3)  , strides = (48,0 ,24,8))

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

similar

In [ ]:
#  no similar method

25 ) Reshape 1D array to 4D array  
input item : 8 bytes  

In [30]:
x = np.asarray(range(1,16) , np.int64)

np.lib.stride_tricks.as_strided(x, shape = (2,2,2,2) , strides = (64,32,16,8))

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15,  0]]]])